### ISSUE TITLE
Replace below logo from Our Clients

### ISSUE THREAD

**Issue by ysushah** [ronakonline/jpexim#2]
![image](https://user-images.githubusercontent.com/62568153/144553890-ae62b60a-59a3-420e-9787-319f959922a7.png)
![image](https://user-images.githubusercontent.com/62568153/144553932-204c13f8-7555-40c2-bcc3-076349e9a559.png)

Remove Silvertech  and Vardhman

above replace with below icon

**Comment by ronakonline** [comment]
commit e5ab2701dc5d876ae7d52df6887bc7b80ebd36da
