### ISSUE TITLE
Change below Text

### ISSUE THREAD

**Issue by ysushah** [ronakonline/jpexim#6]
Remove photo from the last of page (We are one yet we are many) put this photo in slider 
JP Exim and group is a very well-known in Textile Industry
Number= +91 6353464532
Mail= info@jpexim.in
Location= E-03, First floor, Kalavad marketing Yard,
Kalavad (Gujrat) India

**Comment by ronakonline** [comment]
commit f27409b84df0f68c3ba51fa3357e7dadf2b5ac38
![image](https://user-images.githubusercontent.com/32793372/144576173-5ffcff59-1349-41b5-97ce-aeb426f4593a.png)
